"""The frozen tau(n) table must be bit-reproducible from its sealed Monte-Carlo
parameters. We regenerate the low-n prefix (n=2..16) with the exact frozen
procedure (single rng(GATE_NULL_MC_SEED), n ascending contiguous from 2) and
assert it equals the committed fixture entry-for-entry. The full table is
generated by scripts/gen_tau_table.py.

Requires numpy==1.26.4 (the table was sealed under it).
"""

import json
import os

import numpy as np
import pytest

from nachocausal import gate, thresholds

pytestmark = pytest.mark.skipif(
    np.__version__ != thresholds.PINNED_NUMPY,
    reason=f"tau table sealed under numpy=={thresholds.PINNED_NUMPY}",
)

FIX = os.path.join(os.path.dirname(__file__), "..", "nachocausal", "fixtures",
                   "tau_table.json")


def _regen_prefix(n_stop, rng, reps):
    """Reproduce build_tau but stop early at n_stop (same rng stream from 2)."""
    from nachocausal import estimator
    q = 1.0 - thresholds.GATE_ALPHA
    out = {}
    for n in range(2, n_stop + 1):
        vals = np.fromiter(
            (estimator.improvement(rng.random(n)) for _ in range(reps)),
            dtype=float, count=reps)
        out[n] = float(np.quantile(vals, q))
    return out


def test_fixture_params_match_sealed_thresholds():
    doc = json.load(open(FIX))
    p = doc["params"]
    assert p["alpha"] == thresholds.GATE_ALPHA
    assert p["mc_seed"] == thresholds.GATE_NULL_MC_SEED
    assert p["mc_reps"] == thresholds.GATE_NULL_MC_REPS
    assert p["n_max"] == thresholds.GATE_TAU_N_MAX
    assert len(doc["tau"]) == thresholds.GATE_TAU_N_MAX - 1  # n = 2..n_max


def test_tau_prefix_bit_reproducible():
    rng = np.random.default_rng(thresholds.GATE_NULL_MC_SEED)
    regen = _regen_prefix(16, rng, thresholds.GATE_NULL_MC_REPS)
    for n, val in regen.items():
        assert gate.tau(n) == val, f"tau({n}) fixture {gate.tau(n)} != regen {val}"
